version: '3'

services:

  mongo-db:
    container_name: mongo-db
    image: mongo:4.0
    networks:
      - hisp-mapping-network
      - mongo_backup
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

networks:
  hisp-mapping-network:
    name: hisp-mapping-network
  mongo_backup:
    name: mongo_backup
    driver: overlay
    attachable: true

volumes:
  mongo-data: